import { getScenario } from "./scenarios";
import type { Aircraft, Injection, LogEvent, Observation, Recommendation, SimState } from "./types";
let seq=0; const uid=(p:string)=>`${p}-${++seq}`;
const log=(time:number,type:LogEvent["type"],message:string,severity?:LogEvent["severity"]):LogEvent=>({id:uid("e"),time,type,message,severity});
export function initialState(scenarioId="runway",mode:SimState["mode"]="advisory"):SimState { const s=getScenario(scenarioId); return {status:"idle",time:0,speed:1,mode,scenarioId,aircraft:structuredClone(s.aircraft),vehicles:structuredClone(s.vehicles),weather:{...s.initialWeather},logs:[log(0,"system",`Scenario loaded · seed ${s.seed}`)],observations:[],recommendations:[],incidents:[],prevented:0,interlocks:0,maxWorkload:0}; }
const moveAircraft=(a:Aircraft,dt:number)=>{a.previous={...a.position}; if(a.phase==="go-around"){a.position.x=Math.min(98,a.position.x+.12*dt);a.altitude=Math.min(a.targetAltitude,a.altitude+45*dt);return;} if(a.phase==="approach"||a.phase==="short-final"){a.position.x-=a.speed*dt;a.altitude=Math.max(0,a.altitude-14*dt);if(a.position.x<72)a.phase="short-final";} if(a.phase==="landing-roll"){a.position.x-=a.speed*dt;if(a.position.x<18){a.phase="taxi-in";a.position.y+=.05*dt;}} if(a.phase==="take-off-roll"){a.position.x+=a.speed*dt;a.speed=Math.min(.32,a.speed+.004*dt);if(a.position.x>78){a.phase="climb";a.altitude+=45*dt;}}};
function observe(state:SimState,agent:string,severity:Observation["severity"],category:string,entities:string[],text:string,evidence:string[],consequence:string,ttc:number,action:Recommendation["action"],targetId:string){
 if(state.observations.some(o=>o.category===category&&o.entities.join()===entities.join()))return;
 const o:Observation={id:uid("obs"),agent,time:state.time,severity,entities,category,observation:text,evidence,consequence,timeToConflict:ttc,confidence:.98,recommendedAction:action};state.observations.unshift(o);
 const related=state.observations.filter(x=>x.category===category||x.entities.some(e=>entities.includes(e))).slice(0,3);
 const r:Recommendation={id:uid("rec"),observationIds:related.map(x=>x.id),title:text,explanation:`${related.map(x=>x.agent).join(" + ")} correlated live position, clearance and trajectory state.`,severity,action,targetId,status:"active",createdAt:state.time};state.recommendations.unshift(r);
 state.logs.push(log(state.time,"agent",`${agent}: ${text}`,severity));
}
function inject(state:SimState,inj:Injection){
 const a=state.aircraft[0],v=state.vehicles[0];
 if(inj.kind==="occupied-landing") { a.clearance="CLEARED TO LAND RWY 27"; state.logs.push(log(state.time,"atc",`${a.callSign}, cleared to land Runway 27`,"warning"),log(state.time,"pilot",`Cleared to land 27, ${a.callSign}`)); }
 if(inj.kind==="crossing-takeoff"){if(a){a.clearance="CLEARED FOR TAKE-OFF";a.phase="take-off-roll";}if(v){v.authorised=true;v.stopped=false;}state.logs.push(log(state.time,"atc",`${a?.callSign}, cleared for take-off. ${v?.label??"Traffic"}, cross Runway 27`,"critical"));}
 if(inj.kind==="wrong-readback"){a.targetAltitude=2000;a.clearance="DESCEND 3000";state.logs.push(log(state.time,"atc",`${a.callSign}, descend 3,000 feet`),log(state.time,"pilot",`Descending 2,000 feet, ${a.callSign}`,"warning"));}
 if(inj.kind==="weather"){state.weather={visibility:1.2,windSpeed:31,crosswind:24,condition:"Heavy rain"};state.logs.push(log(state.time,"system","Weather update: visibility 1.2 km, crosswind 24 kt","warning"));}
 if(inj.kind==="callsign")state.logs.push(log(state.time,"atc","METRO 425, descend 2,000 — correction, METRO 452","warning"));
}
function rules(s:SimState){
 const arrival=s.aircraft.find(a=>a.kind==="arrival"&&(a.phase==="approach"||a.phase==="short-final")); const occupant=s.aircraft.find(a=>a.phase==="landing-roll");
 if(arrival?.clearance?.includes("LAND")&&occupant){const t=Math.max(0,(arrival.position.x-18)/Math.max(.01,arrival.speed));observe(s,"Runway Safety","critical","runway-occupancy",[arrival.id,occupant.id],`Landing clearance conflicts with occupied Runway 27`,[`${occupant.callSign} remains in protected zone`,`${arrival.callSign} is ${arrival.phase}`,`Threshold in ${Math.round(t)}s`],"Runway collision or forced late go-around",t,"go-around",arrival.id);}
 const dep=s.aircraft.find(a=>a.phase==="take-off-roll"),v=s.vehicles.find(x=>x.authorised&&!x.stopped);if(dep&&v){observe(s,"Ground Agent","critical","runway-crossing",[dep.id,v.id],"Take-off roll conflicts with runway crossing",[`${dep.callSign} accelerating`,`${v.label} crossing clearance active`],"Runway collision",25,"cancel-takeoff",dep.id);}
 const wrong=s.aircraft.find(a=>a.clearance==="DESCEND 3000"&&a.targetAltitude===2000);if(wrong)observe(s,"Communication Agent","warning","readback-mismatch",[wrong.id],`Incorrect altitude readback by ${wrong.callSign}`,["Issued 3,000 ft","Read back 2,000 ft","Target state changed to 2,000 ft"],"Potential loss of separation",42,"correct-altitude",wrong.id);
 if(s.weather.visibility<2&&arrival)observe(s,"Weather Agent","warning","unsafe-weather",[arrival.id],"Approach is outside simulated weather limits",[`${s.weather.visibility} km visibility`,`${s.weather.crosswind} kt crosswind`,`${arrival.callSign} continuing ${arrival.phase}`],"Unstable approach",38,"go-around",arrival.id);
 if(s.logs.filter(e=>s.time-e.time<12).length>6)observe(s,"Workload Agent","warning","frequency-overload",[],"Controller workload is high",["High transmission rate","Multiple unresolved alerts"],"Delayed safety response",35,"hold",arrival?.id??s.aircraft[0]?.id);
}
export function tick(prev:SimState,dt=.25):SimState {if(prev.status!=="running")return prev;const s=structuredClone(prev);s.time+=dt;const sc=getScenario(s.scenarioId);sc.injections.filter(i=>i.at>prev.time&&i.at<=s.time).forEach(i=>inject(s,i));s.aircraft.forEach(a=>moveAircraft(a,dt));s.vehicles.forEach(v=>{if(!v.stopped&&v.authorised){v.position.y+=v.speed*dt;}});s.runwayOccupiedBy=s.aircraft.find(a=>["landing-roll","take-off-roll"].includes(a.phase))?.id;s.maxWorkload=Math.max(s.maxWorkload,Math.min(100,25+s.aircraft.length*10+s.recommendations.filter(r=>r.status==="active").length*15+s.logs.filter(e=>s.time-e.time<15).length*4));rules(s);
 for(const r of s.recommendations.filter(x=>x.status==="active"&&x.severity==="critical")){if(s.mode==="interlock"&&s.time-r.createdAt<.3){r.status="blocked";s.interlocks++;s.logs.push(log(s.time,"agent",`SAFETY INTERLOCK: blocked unsafe clearance — ${r.title}`,"critical"));}else if(s.time-r.createdAt>25&&!s.incidents.includes(r.id)){s.incidents.push(r.id);s.logs.push(log(s.time,"incident",`SIMULATED INCIDENT: ${r.title}`,"critical"));}}
 if(s.time>=sc.duration)s.status="ended";return s; }
export function resolve(prev:SimState,id:string,decision:"accepted"|"rejected"|"modified"):SimState {const s=structuredClone(prev),r=s.recommendations.find(x=>x.id===id);if(!r)return s;r.status=decision;r.responseTime=s.time-r.createdAt;const a=s.aircraft.find(x=>x.id===r.targetId);const v=s.vehicles.find(x=>x.id===r.targetId);if(decision!=="rejected"){if(r.action==="go-around"&&a){a.phase="go-around";a.targetAltitude=3000;a.clearance="GO AROUND";}if(r.action==="cancel-takeoff"&&a){a.phase="holding-short";a.speed=0;}if(r.action==="stop-vehicle"&&v)v.stopped=true;if(r.action==="correct-altitude"&&a)a.targetAltitude=3000;if(r.action==="hold"&&a)a.phase="holding";s.prevented++;}s.logs.push(log(s.time,"decision",`${decision.toUpperCase()}: ${r.title}`,decision==="rejected"?"warning":"info"));return s;}
export const score=(s:SimState)=>({safety:Math.max(0,100-s.incidents.length*35),awareness:Math.min(100,55+s.prevented*12),communication:Math.min(100,60+s.recommendations.filter(r=>r.action==="correct-altitude"&&r.status!=="rejected").length*35),response:Math.max(30,100-Math.round(s.recommendations.reduce((n,r)=>n+(r.responseTime??20),0)/Math.max(1,s.recommendations.length))*2),decisions:Math.max(20,100-s.recommendations.filter(r=>r.status==="rejected").length*20)});
