import type { Aircraft, Scenario } from "./types";
const arrival=(id:string,callSign:string,y=50):Aircraft=>({id,callSign,type:"A320",kind:"arrival",position:{x:94,y},previous:{x:94,y},altitude:1100,targetAltitude:0,heading:270,targetHeading:270,speed:0.23,phase:"approach",runway:"27"});
const departure=(id:string,callSign:string,y=50):Aircraft=>({id,callSign,type:"B738",kind:"departure",position:{x:21,y:y+2},previous:{x:21,y:y+2},altitude:0,targetAltitude:5000,heading:270,targetHeading:270,speed:0.08,phase:"holding-short",runway:"27"});
const base={duration:150,initialWeather:{visibility:8,windSpeed:12,crosswind:5,condition:"VMC"}};
export const scenarios:Scenario[]=[
 { ...base,id:"runway",name:"Runway Occupied",short:"Arrival cleared while traffic remains on Runway 27",seed:2701,aircraft:[arrival("a1","SKY 482"),{...departure("a2","NOVA 71"),position:{x:43,y:50},previous:{x:43,y:50},phase:"landing-roll",speed:.06}],vehicles:[],injections:[{at:18,id:"land",kind:"occupied-landing"}]},
 { ...base,id:"crossing",name:"Take-off & Crossing",short:"Departure roll conflicts with an airport vehicle",seed:2702,aircraft:[departure("a1","JET 614")],vehicles:[{id:"v1",label:"OPS 3",position:{x:52,y:34},route:[{x:52,y:34},{x:52,y:66}],routeIndex:0,speed:.09,authorised:false,stopped:false}],injections:[{at:14,id:"cross",kind:"crossing-takeoff"}]},
 { ...base,id:"readback",name:"Incorrect Altitude Readback",short:"A wrong readback creates converging altitude profiles",seed:2703,aircraft:[arrival("a1","EAGLE 52",42),{...arrival("a2","EAGLE 25",59),altitude:3000,targetAltitude:3000,phase:"holding"}],vehicles:[],injections:[{at:12,id:"readback",kind:"wrong-readback"}]},
 { ...base,id:"weather",name:"Weather & Unstable Approach",short:"Crosswind and visibility deteriorate on final",seed:2704,aircraft:[arrival("a1","COAST 218")],vehicles:[],injections:[{at:15,id:"wx",kind:"weather"},{at:28,id:"land",kind:"occupied-landing"}]},
 { ...base,id:"cascade",name:"High-Workload Cascade",short:"Overlapping runway, radio, vehicle and weather threats",seed:2705,aircraft:[arrival("a1","METRO 452",48),{...departure("a2","METRO 425"),position:{x:45,y:50},previous:{x:45,y:50},phase:"landing-roll"},departure("a3","ORBIT 90",61)],vehicles:[{id:"v1",label:"FUEL 8",position:{x:61,y:33},route:[{x:61,y:33},{x:61,y:66}],routeIndex:0,speed:.07,authorised:false,stopped:false}],injections:[{at:8,id:"call",kind:"callsign"},{at:15,id:"read",kind:"wrong-readback"},{at:23,id:"land",kind:"occupied-landing"},{at:32,id:"cross",kind:"crossing-takeoff"},{at:40,id:"wx",kind:"weather"}]},
];
export const getScenario=(id:string)=>scenarios.find(s=>s.id===id)??scenarios[0];
